# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190307_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='featured',
        ),
    ]
