# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_category_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='Bahir Dar', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='jobs.Region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='intersted_in',
            field=models.ManyToManyField(related_name='interested_employees', to='jobs.Category'),
        ),
    ]
