# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190307_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='regiion',
            new_name='region',
        ),
    ]
