# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190307_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='applications',
            field=models.ManyToManyField(blank=True, null=True, related_name='applicants', through='jobs.JobApplication', to='jobs.Job'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='intersted_in',
            field=models.ManyToManyField(blank=True, null=True, related_name='interested_employees', to='jobs.Category'),
        ),
    ]
