# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-08 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_blog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeJobInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.EmployementType')),
                ('job_category', models.ManyToManyField(to='jobs.Category')),
                ('job_leve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobLevel')),
                ('job_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Region')),
            ],
        ),
    ]
