# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-08 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_employeejobinterest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeejobinterest',
            old_name='job_leve',
            new_name='job_level',
        ),
    ]
