# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-10 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20190308_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('start_month', models.CharField(choices=[(b'feb', b'Febraury'), (b'nov', b'November'), (b'sep', b'Septemeber'), (b'jun', b'June'), (b'may', b'May'), (b'jan', b'January'), (b'jul', b'July'), (b'oct', b'October'), (b'apr', b'April'), (b'dec', b'December'), (b'mar', b'March'), (b'aug', b'August')], max_length=10)),
                ('start_year', models.IntegerField()),
                ('end_month', models.CharField(choices=[(b'feb', b'Febraury'), (b'nov', b'November'), (b'sep', b'Septemeber'), (b'jun', b'June'), (b'may', b'May'), (b'jan', b'January'), (b'jul', b'July'), (b'oct', b'October'), (b'apr', b'April'), (b'dec', b'December'), (b'mar', b'March'), (b'aug', b'August')], max_length=10)),
                ('end_year', models.IntegerField()),
                ('description', models.TextField()),
                ('is_currently', models.BooleanField(default=False)),
                ('school', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Degree')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('start_month', models.CharField(choices=[(b'feb', b'Febraury'), (b'nov', b'November'), (b'sep', b'Septemeber'), (b'jun', b'June'), (b'may', b'May'), (b'jan', b'January'), (b'jul', b'July'), (b'oct', b'October'), (b'apr', b'April'), (b'dec', b'December'), (b'mar', b'March'), (b'aug', b'August')], max_length=10)),
                ('start_year', models.IntegerField()),
                ('end_month', models.CharField(choices=[(b'feb', b'Febraury'), (b'nov', b'November'), (b'sep', b'Septemeber'), (b'jun', b'June'), (b'may', b'May'), (b'jan', b'January'), (b'jul', b'July'), (b'oct', b'October'), (b'apr', b'April'), (b'dec', b'December'), (b'mar', b'March'), (b'aug', b'August')], max_length=10)),
                ('end_year', models.IntegerField()),
                ('description', models.TextField()),
                ('is_currently', models.BooleanField(default=False)),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='employeejobinterest',
            old_name='employement_type',
            new_name='employement_types',
        ),
        migrations.RenameField(
            model_name='employeejobinterest',
            old_name='job_category',
            new_name='job_categories',
        ),
        migrations.RenameField(
            model_name='employeejobinterest',
            old_name='job_level',
            new_name='job_levels',
        ),
        migrations.RenameField(
            model_name='employeejobinterest',
            old_name='job_region',
            new_name='job_regions',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='intersted_in',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='school_level',
        ),
        migrations.RemoveField(
            model_name='employeejobinterest',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='about_me',
            field=models.TextField(default='about me default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeejobinterest',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeejobinterest',
            name='pay_period',
            field=models.CharField(max_length=100, choices=[(b'year', b'Per Year'), (b'month', b'Per Month'), (b'day', b'Per Day'), (b'hour', b'Per Hour')], default='year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeejobinterest',
            name='salary_end',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeejobinterest',
            name='salary_start',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='jobs.Employee'),
        ),
        migrations.AddField(
            model_name='skill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobs.Employee'),
        ),
        migrations.AddField(
            model_name='experience',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='jobs.Employee'),
        ),
        migrations.AddField(
            model_name='experience',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Region'),
        ),
        migrations.AddField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='jobs.Employee'),
        ),
        migrations.AddField(
            model_name='education',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Region'),
        ),
    ]
