# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20190311_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeejobinterest',
            name='employement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.EmployementType'),
        ),
        migrations.AlterField(
            model_name='employeejobinterest',
            name='job_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Category'),
        ),
        migrations.AlterField(
            model_name='employeejobinterest',
            name='job_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.JobLevel'),
        ),
        migrations.AlterField(
            model_name='employeejobinterest',
            name='job_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Region'),
        ),
        migrations.AlterField(
            model_name='employeejobinterest',
            name='pay_period',
            field=models.CharField(blank=True, choices=[(b'year', b'Per Year'), (b'month', b'Per Month'), (b'day', b'Per Day'), (b'hour', b'Per Hour')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeejobinterest',
            name='salary_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeejobinterest',
            name='salary_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
