# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20190311_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='how_to_apply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='knowledge_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(1, b'Open'), (2, b'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
