# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_auto_20190312_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
