# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_auto_20190313_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
