# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_job_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[(b'read', b'Read'), (b'unread', b'Unread')], default='unread', max_length=10),
        ),
    ]
