# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_auto_20190313_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ('-status', '-applied_on')},
        ),
        migrations.AlterField(
            model_name='company',
            name='brief_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
