# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_auto_20190314_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='report_to',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='employement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.EmployementType'),
        ),
        migrations.AlterField(
            model_name='job',
            name='number_of_candidates',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
