# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_auto_20190314_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
