# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_auto_20190314_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='jobs.Category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='number_of_candidates',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
