# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_auto_20190314_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='number_of_candidates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
