# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_auto_20190314_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_through_portal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='number_of_candidates',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
