# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_auto_20190322_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='PostCategories',
        ),
    ]
