# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_auto_20190322_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='volunteer_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[(b'read', b'Seen'), (b'unread', b'Not Seen')], default='unread', max_length=10),
        ),
    ]
