# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jobs.functions


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_auto_20190326_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='jobs.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to=jobs.functions.getFileName)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='jobs.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='jobs.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weblinks', to='jobs.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('document', models.FileField(upload_to=jobs.functions.getFileName)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksamples', to='jobs.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='position',
        ),
    ]
