# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import jobs.functions


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_auto_20190515_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to=jobs.functions.getFileName),
        ),
    ]
