# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import jobs.functions


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_auto_20190521_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to=jobs.functions.getFileName),
        ),
    ]
