# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0039_auto_20190522_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_unpaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(default='Addis Ababa', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(default='Addis Ababa', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.Region'),
        ),
    ]
