# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_auto_20190523_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
