# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0041_job_application_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='employementtype',
            name='color',
            field=models.CharField(default='#55a747', max_length=20),
        ),
    ]
