# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 11:09
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0045_auto_20190523_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='education_experience',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='how_to_apply',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='knowledge_skills',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
