# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0047_auto_20190528_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, default='Addis Ababa', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='jobs.Region'),
        ),
    ]
