# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-12 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0050_job_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='is_currently',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='is_currently',
        ),
    ]
