# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0052_auto_20190709_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agerange',
            name='endAge',
            field=models.CharField(max_length=5, verbose_name='Enda Age'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True),
        ),
    ]
