# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0053_auto_20190709_0708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agerange',
            options={'ordering': ('startAge',)},
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_types',
            field=models.ManyToManyField(blank=True, related_name='jobseekers', to='jobs.JobType'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='services_intersted_in',
            field=models.ManyToManyField(blank=True, related_name='jobseekers', to='jobs.JobSeekerService'),
        ),
    ]
