# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0056_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messaged_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
