# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0057_message_messaged_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='Test subject', max_length=200),
            preserve_default=False,
        ),
    ]
