# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0058_message_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('value', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accestokens', to='jobs.Company')),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-status', '-messaged_on')},
        ),
    ]
