# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0059_auto_20190710_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='paramFilter',
            field=models.CharField(default='unread', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='paramQuery',
            field=models.CharField(default='tabor', max_length=300),
            preserve_default=False,
        ),
    ]
