# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-26 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0061_auto_20190719_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[(b'read', b'Seen'), (b'unread', b'Not Seen')], default='unread', max_length=10)),
                ('messaged_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-status', '-messaged_on'),
            },
        ),
    ]
