# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-30 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0063_visitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitcount',
            name='visitDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
