# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jobs.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0031_auto_20190322_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('image', models.FileField(blank=True, null=True, upload_to=jobs.functions.getFileName)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.CharField(blank=True, max_length=10, null=True)),
                ('longitude', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Region')),
            ],
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='event.EventTag'),
        ),
    ]
