# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 00:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20190325_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date(2019, 3, 26)),
            preserve_default=False,
        ),
    ]
