# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[(b'read', b'Read'), (b'unread', b'Unread')], default='unread', max_length=10),
        ),
    ]
