# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 05:37
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20190326_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
