# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20190430_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLinks',
            fields=[
                ('name', models.CharField(choices=[('empskill', 'Employability Skill'), ('youthcareer', 'Youth Career'), ('careerservice', 'Career Service'), ('jobreadines', 'Job Readiness')], max_length=100, primary_key=True, serialize=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Blog')),
            ],
        ),
    ]
