# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_menulinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menulinks',
            options={'verbose_name': 'Menu Link', 'verbose_name_plural': 'Menu Links'},
        ),
    ]
