# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-02 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import jobs.functions


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20190523_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=jobs.functions.getFileName),
        ),
    ]
