# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-02 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20190702_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='event.PostCategories'),
        ),
    ]
