# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20190702_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='blog',
            name='posted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
