# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-19 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import jobs.functions


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_blog_article_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('placement', models.IntegerField(choices=[(2, b'Blog Detail Side'), (1, b'Job Detail Side')])),
                ('image', models.FileField(blank=True, null=True, upload_to=jobs.functions.getFileName)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='article_type',
            field=models.IntegerField(choices=[(2, b'News Article'), (1, b'Blog Post')], default=2),
        ),
    ]
